// <auto-generated />
using System;
using ClientAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientAPI.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20240520123308_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClientAPI.API.Entities+ClientMemberships", b =>
                {
                    b.Property<int>("clientMembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("clientMembershipID"));

                    b.Property<string>("barcode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("buyingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("clientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("firstUsage")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fitnessID")
                        .HasColumnType("int");

                    b.Property<bool>("isValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("membershipID")
                        .HasColumnType("int");

                    b.Property<int>("nrOfEntries")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("clientMembershipID");

                    b.ToTable("ClientMemberships", (string)null);
                });

            modelBuilder.Entity("ClientAPI.API.Entities+Clients", b =>
                {
                    b.Property<int>("clientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("clientID"));

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("avatar")
                        .HasColumnType("longblob");

                    b.Property<string>("barcode")
                        .HasColumnType("longtext");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("notes")
                        .HasColumnType("longtext");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("clientID");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("ClientAPI.API.Entities+Entries", b =>
                {
                    b.Property<int>("entriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("entriesID"));

                    b.Property<string>("barcode")
                        .HasColumnType("longtext");

                    b.Property<int>("clientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fitnessID")
                        .HasColumnType("int");

                    b.Property<int>("insertedByUID")
                        .HasColumnType("int");

                    b.Property<int>("membershipID")
                        .HasColumnType("int");

                    b.HasKey("entriesID");

                    b.ToTable("Entries", (string)null);
                });

            modelBuilder.Entity("ClientAPI.API.Entities+Fitness", b =>
                {
                    b.Property<int>("fitnessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("fitnessID"));

                    b.Property<string>("fitnessName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("fitnessID");

                    b.ToTable("Fitnesses", (string)null);
                });

            modelBuilder.Entity("ClientAPI.API.Entities+Memberships", b =>
                {
                    b.Property<int>("membershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("membershipID"));

                    b.Property<int>("dailyEntriesNumber")
                        .HasColumnType("int");

                    b.Property<int>("fitnessID")
                        .HasColumnType("int");

                    b.Property<int>("fromHour")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("membershipName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("membershipPrice")
                        .IsRequired()
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("toHour")
                        .HasColumnType("int");

                    b.Property<int>("validityDays")
                        .HasColumnType("int");

                    b.Property<int>("validityEntries")
                        .HasColumnType("int");

                    b.HasKey("membershipID");

                    b.ToTable("Memberships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
